### ISSUE TITLE
Callback is not called after verification process is finished

### ISSUE THREAD

**Issue by ChernyshenkoTaras** [idnow/de.idnow.ios.sdk#6]
### Abstract
When I make verification with `IDNowSDK` result callback is not getting called

### Details
I have added all frameworks with `Carthage` according to instruction and start verification by calling 

`@objc public func start(token: String, preferredLanguage: String = "", fromViewController: UIViewController, listener: @escaping IDNowSDKCore.IDNowSDKResultListener)`

However when verification is successfully finished `listener` is not getting called

I make sample project what describe this issue [here](https://github.com/ChernyshenkoTaras/IDNowTest)

```
Environments:
Xcode 11.2.1
IDNowSDK 3.17.0
```

**Steps to reproduce:**

1. Download sample project
2. Run `carthage update --platform iOS` in root folder
3. Open project
4. Change `token` with fresh one generated [here](https://www.idnow.io/products/idnow-autoident/demo/)
5. Launch app and proceed with verification until it will be finished

**Actual result:** `listener` callback is not getting called
**Expected result:**  `listener` callback should be called and pop with result status should appear

**Comment by BilelSelmiIDnow** [comment]
Hi @ChernyshenkoTaras, thanks for reporting this issue.
We fixed this issue and it will be available in the next release mid of February.

**Comment by ChernyshenkoTaras** [comment]
This issue is still reproducible with 3.18.0 version. I updated my sample project to use 3.18.0 version, could you take a look please?

**Comment by BilelSelmiIDnow** [comment]
Hi @ChernyshenkoTaras : the sample project at  https://github.com/ChernyshenkoTaras/IDNowTest is not updated with the latest SDK, can you please update and I will have a look into it

**Comment by BilelSelmiIDnow** [comment]
Hi @ChernyshenkoTaras,  I had a look at your code please use IDNowSDK.shared.start instead of sdk.start and the callback should be called

**Comment by ChernyshenkoTaras** [comment]
@BilelSelmiIDnow but what about Objective-C? We don't have singleton there, so the only way to call `start` with Objective-C it's create `IDNowSDK` object. Same as I did in my sample project.

Will be good if you will add same `shared` singleton to Objective-C or make it possible to call `start` as I did in my sample.

If you will need, I can make sample project with Obj-C too.

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras : It will be good if you make a sample project with Obj-C.

Thanks

**Comment by ChernyshenkoTaras** [comment]
@BilelSelmiIDnow here is a sample project for Objective-C version https://github.com/ChernyshenkoTaras/IDNowTest-Objc

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras : Thank you for your collaboration and creating the sample project.
 please add the following to the Cartfile :  

binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/CB-Xcode-11.2.1.json"
binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/OpenCV2.json"
github "Alamofire/Alamofire" "4.8.2"
github "getsentry/sentry-cocoa" "4.1.0"
github "daltoniam/Starscream"  "3.1.0"

Now you can use [IDNowSDK.shared startWithToken:@"GeneratedToken" preferredLanguage:@"en" fromViewController:self listener:idnowResultListener];

And the callback should be called.

**Comment by ChernyshenkoTaras** [comment]
It works now. Thanks a lot!
